### PR TITLE
Port package to Batch Plugins

### PR DESCRIPTION
**Pull request by Slava**
Hi, Meteor 1.2 will feature the new API for compiling plugins. This PR ports the package to the new API and implements in-memory caching for speed.

Please don't merge this until 1.2 is released ;)

### CODE REVIEW

**Comment by mquandalle** [comment]
Hi Slava, thank you so much for this unexpected PR! I was quietly and distantly following the development of this new API in the meteor core repository and this will help me a lot to port the package to the new API. I see that plugin caching is being worked as a separate meteor package as we speak, so I guess I'll be able to implement it before the next meteor-jade release.

Also Travis CI tests are failing due to the error `unknown package: isobuild:compiler-plugin`, but I guess this is expected.

Thank you again

**Comment by Slava** [comment]
Yes, the failure on travis is expected, since the package is built against Meteor's devel branch which is not released yet.

**Comment by Slava** [comment]
Since 1.2 was released, are you going to look at this again?

**Comment by mquandalle** [comment]
Yes, but I think I still need to switch the caching mechanism to use the new official package?

**Comment by AlbinoGeek** [comment]
@Slava If you push to the fork controlling this PR it will re-run the travis-ci tests.

**Comment by mquandalle** [comment]
@AlbinoGeek I already manually re-scheduled a Travis run and it still fails (you can see [here](https://travis-ci.org/mquandalle/meteor-jade/builds/71511491) that the test was run 9 days ago).

**Comment by AlbinoGeek** [comment]
@mquandalle Oh sorry, interesting that the error is that you can only have one onUse though.

**Comment by mquandalle** [comment]
Meteor-jade [v0.4.5](https://github.com/mquandalle/meteor-jade/releases/tag/v0.4.5) now support the batch plugin API. Thank you for the help @Slava :-)

**Pull request closed without merging**
