### PR TITLE
example jade file for simple-todos tutorial

### PR DESCRIPTION
**Pull request by nickmasso**
I just went through the online [Meteor tutorial](https://www.meteor.com/try) and would have appreciated a Jade example of that simple exercise, since I couldn't bear to do it in straight up HTML.

How about adding an example for the repo? This is how I did it in, but I'm totally open to suggestions on better ways.

### CODE REVIEW

**Comment by mquandalle** [comment]
Good idea! To be honest I known enough Meteor when the tutorial was released and I didn't bother taking a look at it. I don't have have anything to say on the template itself, it's the canonical form :). I just would like you two fix two little things before I can merge this PR:

* Add an empty new line at the end the file
* Add a comment in the beginning of the file explaining where this template came from

**Comment by nickmasso** [comment]
Great!

Something like this at the beginning?

    //- visit https://www.meteor.com/try for the tutorial that produces this jade

**Comment by nickmasso** [comment]
Pushed those changes. Let me know if you need anything else!

**Comment by mquandalle** [comment]
Thank you!

**Pull request merged**
