### PR TITLE
Add mention about bug mentioned in #83

### PR DESCRIPTION
**Pull request by KristerV**
Also added TOC while I was at it.

### CODE REVIEW

**Comment by KristerV** [comment]
interesting, i've just noticed the same issue with https://github.com/raix/Meteor-handlebar-helpers

**Comment by mquandalle** [comment]
Honestly I don't think this bug is meteor-jade fault, but is instead of issue in the meteor constraint solver.

**Comment by KristerV** [comment]
yep seems so.

**Comment by KristerV** [comment]
looks like there's a [pretty big discussion](https://github.com/meteor/meteor/issues/4170) around this. So indeed my PR did not belong here. Shall I revert the changes (and keep the TOC)?

**Comment by mquandalle** [comment]
I'll remove the comment myself when Meteor will fix the problem.

**Comment by KristerV** [comment]
cool. Thought it looks from the conversation that this is design. I hope they arrive at the logical solution in the end.

**Pull request merged**
