### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlbinoGeek**
Highlight that jade impl. is not 100%.

Solving #184 and preventing confusions #183 #176

### CODE REVIEW

**Comment by AlbinoGeek** [comment]
@mquandalle Do you prefer PR master <==> master or with a branch specially named after the issue # that it solves (for future work)?  I plan to try to integrate these features here.

**Comment by AlbinoGeek** [comment]
More branches waiting for merger.  I'll make all my changes on independent branches, and then PR them into my own master when I'm ready to PR them up to you.  Does that work?  Then you only get one master<==>master PR from me at a time, on a specific issue at a time.

**Comment by mquandalle** [comment]
Thanks!

Using feature branches is a good practice.

**Comment by AlbinoGeek** [comment]
@mquandalle I wasn't sure if feature branches could be created here, or if it would create them inside the forked repository or not; the Github for Windows client basically exploded when I told it to interface with an existing repository, so I went and did it manually on git shell.

**Pull request merged**
