### PR TITLE
Rewrite $ attributes directly to dynamic attributes

### PR DESCRIPTION
**Pull request by dalgard**
I believe this would be a powerful addition to `mquandalle:jade`. It might look bigger than it actually is – this feature is fully backwards compatible, since attributes beginning with dollar sign have not been allowed previously.

The idea is to use the name of the `$` attribute directly as the name of a dynamic attribute helper (sans the dollar sign).

My personal use case is to clean up the bindings in [dalgard:viewmodel](https://github.com/dalgard/meteor-viewmodel/), but it could be used for anything.

This code:

```jade
input($bind='value: value')  //- any attribute name beginning with $
```

... simply translates to:

```html
<input {{bind 'value: value'}}>
```

Without the feature, people are forced to use this clunky syntax:

```jade
input($dyn='{{bind "value: value"}}')
```

### CODE REVIEW

**Comment by Rhjulskov** [comment]
+1 for a cleaner syntax for use cases like this!

**Comment by markusgattol** [comment]
I'd love to see that as well since I am using jade/coffee over their verbose counterparts.

**Comment by dalgard** [comment]
Bump...

**Comment by avalanche1** [comment]
+1

**Comment by dalgard** [comment]
I am closing this pull request on account of having reformatted my fork's master branch in order to do a separate release on Atmosphere ([`dalgard:jade`](https://github.com/dalgard/meteor-jade)).

However, I have resubmitted the request as ([#178](https://github.com/mquandalle/meteor-jade/pull/178)) in the continued hope that it will, at some point, find its way into the main package – even when development on `mquandalle:jade` looks like it has come to a bit of a halt.

I don't have any ambitions of taking on the maintenance of Meteor's canonical Jade package, but hope that development will either be resumed or taken over by MDG. Thanks :)

**Comment by avalanche1** [comment]
@dalgard :+1:

**Pull request closed without merging**
