### PR TITLE
Kristian’s fork

### PR DESCRIPTION
**Pull request by mquandalle**
@dalgard has implemented some improvements over this original meteor-jade package as announced in https://forums.meteor.com/t/improved-jade-package/11211. This PR is not intended to be directly merged (because the author didn’t plan that and included things specifics to its fork) but is created to be able to discuss on the code and if needed to reference it.

### CODE REVIEW

**Comment by dalgard** [comment]
As we discussed in the messages on Forums, I think I'll leave the dollar sign syntax and instead look for free-standing helper names – that is, not following by an equals sign – and convert them to dynamic attributes.

**Comment by AlbinoGeek** [comment]
I opened a PR on his side to merge changes backwards into his fork and keep it in sync.

**Comment by mquandalle** [comment]
There are too many conflicts to resolve. I would be happy to merge any improvement to meteor-jade, but for that you need to send a PR, not a giant diverging fork.

**Comment by dalgard** [comment]
I'm looking into this whole thing sometime before New Year's. Sorry for the delay.

**Pull request closed without merging**
